### ISSUE TITLE
Rework the Workbench UI to make the components better integrated and more usable

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/WorkBench#11]

**Comment by jConquest** [comment]
- [ ] Replace welcome page with provis
- [ ] Replace new simulation starter with sim start wizard
- [ ] Reconfigure open simulation to use code from Sim Starter tab for opening a project

**Comment by jConquest** [comment]
From workbenchdashboard.WorkbenchDisplay.java the void pushSimStarterPage() function initiates the creation of the Sim Starter tab that we want to call the new project name pop-up instead

**Comment by jConquest** [comment]
making progress on back-end updating for simStart wiz. Currently the WorkbenchManger.runScript is throwing null pointer whe called by SImStartWiz.configureSimulationButtons

Still in progress of removing all buttons and front end that will no longer be necessary as it will be happening in back end. this error is directly related to this

**Comment by jConquest** [comment]
with todays push to master, this goal has been achieved
