### ISSUE TITLE
Put directory structure in the wiki

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/WorkBench#110]
See issue #89

**Comment by stiber** [comment]
Also adding on, for the server side, a work directory for the repo clone and build and a bin directory to hold the most recent executable and runtime files.

**Comment by stiber** [comment]
Hi @king-shak, is this done, or is this something that we can have a new person pull out of the comments associated with issue #89?

**Comment by king-shak** [comment]
> Hi @king-shak, is this done, or is this something that we can have a new person pull out of the comments associated with issue #89?

Hey professor, this is now done and is under the Implementation Details section of the documentation.

**Comment by stiber** [comment]
Thought so; just wanted to double-check before I closed this.
