### ISSUE TITLE
Fix security issues identified by github

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/WorkBench#14]
## *What kind* of issue is this?
* [X] Bug report
* [ ] Feature request
* [ ] Question not answered in documentation
* [ ] Cleanup needed

This can be accessed from https://github.com/UWB-Biocomputing/BrainGrid/network/alerts

## *What* is affected by this?

Workbench, specifically Tools/Workbench/WorkbenchProject/pom.xml

**Comment by jConquest** [comment]
com.fasterxml.jackson.core:jackson-databind was updated in previous push and is resolved

**Comment by jConquest** [comment]
org.apache.httpcomponents:httpclient updated to 4.5.8 was tested and merged to master

**Comment by jConquest** [comment]
Went through all remaining alerts and ensured we have updated all necessary dependencies. No more alerts for now. This can be closed.
