### ISSUE TITLE
In NLEdit, Print button displays error output

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#23]
Error message displayed as java message box saying "No print service found."

**Comment by karthikvetrivel** [comment]
I was looking into this out of curiosity - is this something that we'd like to keep in the new WorkBench?

**Comment by karthikvetrivel** [comment]
@jConquest ^

**Comment by stiber** [comment]
My $0.02: I'm not sure what we'd like to print from the Workbench; this requires more thought. My guess about the UI is that, if there is a print capability, it should be accessed from nearer the top level.

**Comment by jConquest** [comment]
So I have just tested the print button from NLEdit, and it is fully working now. To clarify, prints out the NLEdit layout image after one sets the inh prob and active neurons
