### ISSUE TITLE
Investigate what action is taken for 3 of the NLEdit ribbon buttons

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#28]
Currently there appears to be three buttons in the NLEdit window's ribbon that do not provide functionality.
1. New Project  (maybe not needed as there is "Clear" button)
2. Open
3. Save

Investigate if this is true or if there is an underlining error that is causing the buttons to take not action when clicked

**Comment by karthikvetrivel** [comment]
Yes, none of the NLEdit ribbon buttons are programmed to do anything.
<img width="1099" alt="Screen Shot 2020-06-28 at 5 30 43 PM" src="https://user-images.githubusercontent.com/24781606/85962345-19912700-b965-11ea-8f2e-226697ab25c5.png">

The Open and Save button are not linked to any methods, so they won't do anything. The New Project button links the newProject() method; however, this method is empty.

**Comment by jConquest** [comment]
We will remove import and export and save and open buttons (comment them out in the code base) It is best to allow the user to import via the provis interaction

**Comment by karthikvetrivel** [comment]
> We will remove import and export and save and open buttons (comment them out in the code base) It is best to allow the user to import via the provis interaction

Removed, will close issue after pull request is approved.
