### ISSUE TITLE
investigate and fix resources issues

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#35]
when running WB the following 5 warnings are produced:

Jul 06, 2020 3:23:11 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "resources/simstarter/css/temp.css" not found.
Jul 06, 2020 3:23:11 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "resources/simstarter/css/tempII.css" not found.
Jul 06, 2020 3:23:11 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "resources/nledit/css/design.css" not found.
Jul 06, 2020 3:23:11 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "resources/workbenchdisplay/css/design.css" not found.
Jul 06, 2020 3:23:11 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "resources/provvisualizer/css/design.css" not found.

all of these files exist in the "resources" directory under /src/main/resources/        but are not being found.

**Comment by karthikvetrivel** [comment]
Took me some time, but some shifts in how we navigate through the file path seem to have worked.
![carbon](https://user-images.githubusercontent.com/24781606/88757632-5f374000-d11b-11ea-8167-147c50031ee5.png)

Pull request has been created, the issue can be closed once accepted.
