### ISSUE TITLE
Investigate remote simulation runtime environment

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#43]
After setting up F5 we want to make sure you can run the simulation.

Then try using the WB remote sim runtime environment, record any issues and success that occurs.

At minimum lets get one simulation to run to completion

**Comment by jConquest** [comment]
From specifying new project to opening the simulation runtime specification window should produce the following output log info: Jul 15, 2020 10:50:13 AM edu.uwb.braingrid.workbench.WorkbenchManager newProject
INFO: Making New Project
Jul 15, 2020 10:50:13 AM edu.uwb.braingrid.workbench.ui.NewProjectDialog <init>
INFO: Opening New Project Dialog for Sim Starter
Jul 15, 2020 10:50:16 AM edu.uwb.braingrid.workbench.WorkbenchManager initProject
INFO: Initializing a New Project: sdfgf
Jul 15, 2020 10:50:16 AM edu.uwb.braingrid.workbench.project.ProjectMgr <init>
INFO: New Project Manager for project: sdfgf
Jul 15, 2020 10:50:16 AM edu.uwb.braingrid.provenance.ProvMgr <init>
INFO: New Provenance Manager for sdfgf
Jul 15, 2020 10:50:17 AM edu.uwb.braingrid.workbench.WorkbenchManager configureSimulation
INFO: Configuring Simulation for sdfgf
Jul 15, 2020 10:50:17 AM edu.uwb.braingrid.workbench.ui.InputConfigClassSelectionDialog <init>
INFO: New InputConfigClassSelectionDialog for sdfgf
Jul 15, 2020 10:50:17 AM edu.uwb.braingrid.workbench.data.DynamicInputConfigurationManager <init>
INFO: New edu.uwb.braingrid.workbench.data.DynamicInputConfigurationManager
Jul 15, 2020 10:50:17 AM edu.uwb.braingrid.workbench.model.DynamicInputConfiguration <init>
INFO: New edu.uwb.braingrid.workbench.model.DynamicInputConfiguration
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.InputConfigClassSelectionDialog okButtonActionPerformed
INFO: Ok Button Clicked
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.InputConfigClassSelectionDialog setConfigXMLDoc
INFO: Start setConfigXMLDoc
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.InputConfigClassSelectionDialog setConfigXMLDoc
INFO: End setConfigXMLDoc
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.InputConfigClassSelectionDialog okButtonActionPerformed
INFO: Ok Button ended
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog <init>
INFO: New edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog for sdfgf
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog$ImportFileButtonListener <init>
INFO: New edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog$ImportFileButtonListener Type: ACTIVE
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog$ImportFileButtonListener <init>
INFO: New edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog$ImportFileButtonListener Type: INHIBITORY
Jul 15, 2020 10:50:19 AM edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog$ImportFileButtonListener <init>
INFO: New edu.uwb.braingrid.workbench.ui.DynamicInputConfigurationDialog$ImportFileButtonListener Type: PROBED
Jul 15, 2020 10:50:22 AM edu.uwb.braingrid.workbench.WorkbenchManager specifyScript
INFO: Specifying Script
Jul 15, 2020 10:50:22 AM edu.uwb.braingrid.workbench.ui.ScriptSpecificationDialog <init>
INFO: New ScriptSpecificationDialog

**Comment by jConquest** [comment]
sounds like the issue is occurring in this file:

edu.uwb.braingrid.workbench.project.ProjectMgr

**Comment by jConquest** [comment]
If you cannot find a good workaround in fixing the new project window issues, try out on Windows and see if that helps. Please try to add notes of what you tried. And of course, you can set up the remote desktop app and try fully on ubuntu in lab.

**Comment by jConquest** [comment]
Here is a link to a Youtube video put out by UWB IT to connect to linux lab using putty https://www.youtube.com/watch?v=MnVFQtyPs38&feature=youtu.be

**Comment by jConquest** [comment]
I gave several attempts to log into the linux lab myself, but putty was not able to find the host name for any of the linux lab machines that I am aware of. Could this be because of some access issue with summer quarter and not being registered for css classes? or is the linux lab just total kaput?

**Comment by karthikvetrivel** [comment]
@jConquest I was able to log into the Linux Lab machines. I'm pretty sure they're still online.

**Comment by karthikvetrivel** [comment]
@jConquest @stiber 
<img width="563" alt="Screen Shot 2020-07-21 at 12 28 08 PM" src="https://user-images.githubusercontent.com/24781606/88097895-bf434a80-cb4d-11ea-9514-76ada1e804fd.png">

Without any modifications, the program does not compile on the CSS machines. Just something to take note of. It seems like the right JavaFX JDK is not installed on the servers (which maybe I'll have to do?).

**Comment by karthikvetrivel** [comment]
It seems like I can't install another JRE because I don't have sudo permissions either. We can talk about this more during our meeting tomorrow.

**Comment by stiber** [comment]
That video was from Prof. Pisan, and is a bit dated; perhaps you were trying to connect to the old Linux machines, which have been retired. The latest information is in the [CSS wiki](http://depts.washington.edu/cssuwb/wiki/connecting_to_the_linux_lab). I recommend you use the free MobaXterm, rather than putty.

**Comment by karthikvetrivel** [comment]
Using SDKMAN to install OpenJDK + OpenJFX 8 on Ubuntu. 

StackOverflow post with instructions: https://stackoverflow.com/questions/61783369/install-openjdkopenjfx-8-on-ubuntu-20

SDKMAN! installation guide: https://sdkman.io/install

Not sure if this would be the best solution for a server-wide dependency issue. But... it allows OpenJDK and OpenJFX to run together.

**Comment by jConquest** [comment]
I was able to connect to the linux lab and successfully run a simulation to completion without having to set up external dependencies. Let's talk about this tomorrow @karthikvetrivel to compare notes.

**Comment by jConquest** [comment]
@karthikvetrivel has this issue persisted for you?

**Comment by jConquest** [comment]
Test with MacOS

**Comment by jConquest** [comment]
Where does upload files go on local machine

**Comment by jConquest** [comment]
Files downloaded from remote server are placed in target folder of workbench executed under the "Projects" directory. There should be a "Provenance" directory in each sub-directory in "Projects" but this does not occur. Further investigation into Provenance .ttl file creation and copying needs investigation.

**Comment by karthikvetrivel** [comment]
Still having trouble on MacOS--try testing it on your own system Joe?

**Comment by jConquest** [comment]
Remote simulation is running flawlessly now.
