### ISSUE TITLE
Need to decide on a single location for simulation results file name specification

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/WorkBench#44]
Right now, the simulation results file name can be specified on either the command line or in the parameter file. One would have to look at the BrainGrid code in detail to see which has precedence. We should pick one. This needs to be done in BG first, then Workbench can be modified to follow. If the decision is made to use the command line, then WB needs to ensure not only to construct the correct command line, but also that this information still makes it into the provenance information.

**Comment by stevecl5** [comment]
@stiber Workbench and the existing configfiles in the Graphitti repo already use the parameter file to specify the results file name. I think using the parameter file exclusively would be the simplest option. Removing the command line option (for specifying the results file) in Graphitti should not have any effect on Workbench.

**Comment by stiber** [comment]
OK, I've added this as an issue in Graphitti.

**Comment by stevecl5** [comment]
Closing this issue since there are no action items for Workbench.
