### ISSUE TITLE
ProjectMgr.java ProjectManager.java and Project.java require investigation and clean-up

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#48]
From ProjectMgr.java : 
"// CLEANED (but soon to be dead... recommended that the class be maintained 
//          during testing of its replacement)"

From ProjecManager.java : 
"// NOT CLEANED (Still Implementing / Testing / JavaDocs / Class Header)"

From Project.java : 
"// CLOSED FOR MODIFICATION
// NOT CLEANED
// FIX THIS!!! (Needs JavaDocs / Line Comments)"

**Comment by stevecl5** [comment]
`ProjectMgr`, `ProjectManager`, and `Project` are merged into the new `Simulation` class in the [directory-structure-update](/UWB-Biocomputing/WorkBench/tree/directory-structure-update) branch.
