### ISSUE TITLE
NLEdit pattern generation needs reworking

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#49]

**Comment by jConquest** [comment]
should keep it associated with pattern generation, but clearly not with grid re-sizing

**Comment by jConquest** [comment]
Repeat and alternate need investigation both in their response to user interaction and the code being called

**Comment by stiber** [comment]
Probably needs improved input validation. Remember that the two text fields are independent of the two radio buttons, and are applicable regardless of which radio button is selected. Each decimal should be <= 1, and their sum should be <= 1.

**Comment by karthikvetrivel** [comment]
Working on this right now. I'm attempting to fix some of the CSS issues as well.

**Comment by karthikvetrivel** [comment]
Update:
I've fixed some CSS issues that make the Arrange Probes and Generate Pattern tabs easier to understand. I found the pattern generation code, but honestly, It is quite complex and I'll need more time to debug it.

**Comment by jConquest** [comment]
- [ ] Document procedure for using generate pattern with arrange probes and upload to github documentation for NLEdit
- [ ] Adjust layout of bottom tool bar in NLEdit to A) separate the Generate Pattern and Arrange Probes button from the other buttons in the tool bar   B) add some spacing between all components of the bottom tool bar to increase legibility

**Comment by jConquest** [comment]
By completing the two tasks above to add clarity to NLEdit pattern generation functionality to users; this issue can be resolved per our discussion from last weeks meeting.

**Comment by karthikvetrivel** [comment]
> By completing the two tasks above to add clarity to NLEdit pattern generation functionality to users; this issue can be resolved per our discussion from last weeks meeting.

My bad Joe, I just saw this. Does NLEdit currently have any documentation written on it? I couldn't find it. I can fix the layout on the bottom now though.

**Comment by karthikvetrivel** [comment]
<img width="1125" alt="Screen Shot 2020-08-18 at 10 24 01 PM" src="https://user-images.githubusercontent.com/24781606/90595351-8b396480-e1a1-11ea-83ac-0286336926e5.png">
I kept the labels close to the TextFields intentionally to keep things clear.

**Comment by jConquest** [comment]
@karthikvetrivel that looks great! Much better legibility for the tool bar. There is not any documentation as of yet

**Comment by jConquest** [comment]
Resizing continues to have issues with ratio not matching number of added inhibitory or active neurons. The layout may also not fully maximize the distance between like and unlike neurons.

**Comment by karthikvetrivel** [comment]
I wrote a little more for this, where should I put it?

**Comment by jConquest** [comment]
Great @karthikvetrivel we will add that to the "Running Simulations" documentation which is the docs directory in the repo. It can go just before or after the section talking about importing layout files. We will also need to import a photo or two to illustrate what we are talking about. Keep in mind that the current documentation in "Running Simulations" will be updated with the completion of the simulation wizard. We can see this addition to the documentation as the first step in this.
