### ISSUE TITLE
NLEdit resizing has issues 

### ISSUE THREAD

**Issue by jConquest** [UWB-Biocomputing/WorkBench#50]

**Comment by jConquest** [comment]
scaling method does not make sense, or needs more clarity

**Comment by stiber** [comment]
The goal is that someone who wants to create a large simulation can define a pattern of neuron types and probed neurons for a small grid, and then resize/repeat it _N_ by _M_ times to make a much larger grid of neurons.

**Comment by karthikvetrivel** [comment]
I've been looking into it, and the resizing works pretty well. For example, a 5x5 with a certain pattern repeats well (4 times, as it should) when scaled to 10x10. The resizing is only questionable when the factors to scale by don't match up properly. Am I missing something?

Is this something we should catch in the user input if it doesn't scale properly?

**Comment by jConquest** [comment]
Yellow is caused when neurons set up to be multiple things

**Comment by jConquest** [comment]
This does not make sense to have an excited and inhibited neuron set as the same, hence we should most likely prevent this from occuring

**Comment by jConquest** [comment]
Please disregard the two previous, it is okay for them to be inhibitory and active

**Comment by karthikvetrivel** [comment]
Is this good to close? I don't think we found any issue with this earlier

**Comment by jConquest** [comment]
We can close this issue, and I will add an action item to the other NLEdit card to include a description of resizing in the documentation to be added
