### ISSUE TITLE
Clean up file creation and organization

### ISSUE THREAD

**Issue by torisalvatore** [UWB-Biocomputing/WorkBench#71]
the current program has copies of XMLS and other files created in all sorts of places. There are files being saved to my home directory, within the workbench project, and within subdirectories half a dozen deep in the workbench project-- all for the same simulation run. Then, the workbench project saves the universalprovenance.ttl file in WorkBench/WorkbenchProject/projects, which is deeper than some of the xmls created in WorkbenchProject/. Despite all of this, the universal provenance file still has problems creating the proper file paths with which to run the simulation. This could solve other issues further down the pipeline.

**Comment by stevecl5** [comment]
subsumed by Issue #89
