### ISSUE TITLE
Implement intermediate directory structure

### ISSUE THREAD

**Issue by stevecl5** [UWB-Biocomputing/WorkBench#92]
Linked to Issue #89

This issue describes the first set of changes to the Workbench directory structure.

Goals:
- Workbench runtime files are separate from data files (e.g. so they can be managed by a system administrator)
- Project and simulation data directories can be user-specified (locations saved in .workbench directory and loaded during WB startup)
- Simulator local repo and executable (on the simulation machine) are separate from WB data and runtime files
- Simulation script and all input/output files (on the simulation machine) are stored in a simulation data directory and organized by simulation name. The simulation data directory is stored in the same location, relative to the simulation machine, whether the simulation is run locally or remotely.
- Templates directory is removed (the resources are now accessed directly from the JAR file)
- Log files are moved to logs directory

The intermediate directory structure is shown below.

Install Directory*
-------------------
```
/usr/local/bin/Workbench/
├── lib/
└── GraphittiWorkbench.jar
```
\* read-only, portable

Projects Directory
-------------------
```
WorkbenchProjects/
├── artifacts/
├── BrainGridRepos/
└── projects/
    ├── sim1/
    │   ├── configfiles/
    │   │   ├── NList/
    │   │   │   ├── act.xml
    │   │   │   ├── inh.xml
    │   │   │   └── prb.xml
    │   │   └── sim1.xml
    │   ├── provenance/
    │   │   └── sim1.ttl
    │   ├── scripts/
    │   │   ├── sim1_script1.sh
    │   │   ├── sim1_v1_scriptStatus.txt
    │   │   ├── sim1_v1_SHA1Key.txt
    │   │   └── sim1_v1_simStatus.txt
    │   └── sim1.xml
    ├── sim2/
    └── UniversalProvenance.ttl
```

Simulations Directory
-------------------
```
.workbench/simulations/
├── sim1/
│   ├── configfiles/
│   │   ├── NList/
│   │   │   ├── act.xml
│   │   │   ├── inh.xml
│   │   │   └── prb.xml
│   │   └── sim1.xml
│   ├── results/
│   │   └── sim1-out.xml 
│   ├── sim1_script1.sh
│   ├── sim1_v1_output.txt
│   ├── sim1_v1_scriptStatus.txt
│   ├── sim1_v1_SHA1Key.txt
│   └── sim1_v1_simStatus.txt
└── sim2/
```

Workbench Directory
-------------------
```
.workbench/
├── logs/
│   ├── provOverhead.txt
│   ├── WD-log.0
│   └── WD-WorkbenchManager-log.0
└── user.json
```

**Comment by stiber** [comment]
Looks good overall. Some nitpicking:

- For `WorkbenchProjects`:
  - `projects` directory really contains a set of simulations; probably should be named that (I know that right now WB uses that name for simulations, but we should change that).
  - This directory contains a set of simulations, right? I think we should call that a "project", singular. The user should be able to name a project, which should be reflected in the directory name. Maybe we should call it `[userdefinedname].workbenchproject`? On a MacOS or Windows machine, it should be possible to make that directory look like a file (or at least have a custom icon).
- For `workbench/simulations/`:
  - I don't think we need the extra level of directory; perhaps it could just be `[userdefinedname].workbenchsimulations`? In this case, plural makes sense.

It may be the case that the user defined name for these directories isn't yet implemented in the WB UI, so we'd have to have a fixed name right now, set up so it can be changed easily to a user defined one when the WB UI catches up.
